# -*- coding: utf-8 -*-
"""Day28_Pose_Graph_Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Y9Y4__3utbD4byIm8rxn0Ch7QER44WU
"""

## ═══════════════════════════════════════════════════════════
## CELL 1: Setup and Ground Truth
## ═══════════════════════════════════════════════════════════

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import least_squares

# ─── Ground Truth Poses ───────────────────────────────────
# 8 poses forming a square path (2D for simplicity)
# Each pose = [x, y, theta]  (position + heading angle)
# Robot walks: right → right → down → down → left → left → up → up
# Ends back where it started — a perfect loop

ground_truth = np.array([
    [0.0, 0.0, 0.0],          # Pose 0: start at origin, facing right
    [1.0, 0.0, 0.0],          # Pose 1: moved 1m right
    [2.0, 0.0, -np.pi/2],     # Pose 2: moved 1m right, turned to face down
    [2.0, -1.0, -np.pi/2],    # Pose 3: moved 1m down
    [2.0, -2.0, np.pi],       # Pose 4: moved 1m down, turned to face left
    [1.0, -2.0, np.pi],       # Pose 5: moved 1m left
    [0.0, -2.0, np.pi/2],     # Pose 6: moved 1m left, turned to face up
    [0.0, -1.0, np.pi/2],     # Pose 7: moved 1m up — should be near pose 0!
])

num_poses = len(ground_truth)

print(f"Ground truth: {num_poses} poses forming a 2m x 2m square")
print(f"Start: {ground_truth[0]}")
print(f"End:   {ground_truth[-1]} (should be close to start)")

## ═══════════════════════════════════════════════════════════
## CELL 2: Create Noisy VO Measurements
## ═══════════════════════════════════════════════════════════

def compute_relative_pose(pose_from, pose_to):
    """
    Compute the relative measurement between two poses.
    This is what VO gives us: "to get from pose A to pose B,
    move by (dx, dy) and rotate by dtheta."

    Think of it like: I'm standing at A, facing some direction.
    How far forward/sideways do I need to walk, and how much
    do I need to turn, to reach B?
    """
    dx = pose_to[0] - pose_from[0]       # x difference in world frame
    dy = pose_to[1] - pose_from[1]       # y difference in world frame
    dtheta = pose_to[2] - pose_from[2]   # rotation change

    # Rotate the translation into pose_from's local frame
    # WHY: VO measures motion in the CAMERA'S frame, not the world
    # Same reason we did R_global @ t_step in vo_node
    cos_t = np.cos(pose_from[2])
    sin_t = np.sin(pose_from[2])
    local_dx = cos_t * dx + sin_t * dy   # forward in local frame
    local_dy = -sin_t * dx + cos_t * dy  # sideways in local frame

    return np.array([local_dx, local_dy, dtheta])


# ─── Generate VO measurements with noise ──────────────────
# Each measurement = true relative pose + random noise
# This simulates what real VO gives you: correct on average,
# but slightly wrong every time. Errors accumulate.

np.random.seed(42)                # reproducible results

# Noise level — how much each VO measurement is off
# 0.05m position noise, 0.03 radian (~2°) angle noise
# Real VO is roughly this noisy on each step
noise_std = np.array([0.05, 0.05, 0.03])

# Create measurements between consecutive poses (VO edges)
vo_measurements = []
for i in range(num_poses - 1):
    # True relative motion between pose i and pose i+1
    true_relative = compute_relative_pose(ground_truth[i], ground_truth[i+1])

    # Add noise — this is the VO measurement error
    noise = np.random.randn(3) * noise_std
    noisy_relative = true_relative + noise

    vo_measurements.append(noisy_relative)
    print(f"VO edge {i}→{i+1}: dx={noisy_relative[0]:.3f}, "
          f"dy={noisy_relative[1]:.3f}, dθ={np.degrees(noisy_relative[2]):.1f}°")

print(f"\n{len(vo_measurements)} VO measurements created (each slightly noisy)")

## ═══════════════════════════════════════════════════════════
## CELL 3: Chain Measurements → Drifted Trajectory
## ═══════════════════════════════════════════════════════════

def chain_poses(start_pose, measurements):
    """
    Chain relative measurements to build a trajectory.
    This is EXACTLY what vo_node does:
      t_global = t_global + R_global @ t_step
      R_global = R_global @ R_step

    In 2D it's simpler — just rotate local motion by heading angle
    and add to current position.

    The problem: each measurement has small error.
    Chain 8 small errors → big accumulated drift.
    Like copying a photocopy of a photocopy — quality degrades.
    """
    poses = [start_pose.copy()]

    for meas in measurements:
        prev = poses[-1]

        # Rotate local measurement into world frame using current heading
        cos_t = np.cos(prev[2])
        sin_t = np.sin(prev[2])
        world_dx = cos_t * meas[0] - sin_t * meas[1]
        world_dy = sin_t * meas[0] + cos_t * meas[1]

        # New pose = previous + world-frame motion
        new_pose = np.array([
            prev[0] + world_dx,
            prev[1] + world_dy,
            prev[2] + meas[2]
        ])
        poses.append(new_pose)

    return np.array(poses)


# Chain the noisy VO measurements starting from the true origin
drifted_poses = chain_poses(ground_truth[0], vo_measurements)

# Show the drift — how far is the last pose from where it should be?
drift = drifted_poses[-1] - ground_truth[-1]
print(f"Final pose (ground truth): x={ground_truth[-1][0]:.3f}, y={ground_truth[-1][1]:.3f}")
print(f"Final pose (drifted):      x={drifted_poses[-1][0]:.3f}, y={drifted_poses[-1][1]:.3f}")
print(f"Drift: dx={drift[0]:.3f}m, dy={drift[1]:.3f}m, "
      f"dθ={np.degrees(drift[2]):.1f}°")
print(f"Total position drift: {np.sqrt(drift[0]**2 + drift[1]**2):.3f}m")

## ═══════════════════════════════════════════════════════════
## CELL 4: Visualize Ground Truth vs Drifted
## ═══════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# ─── Plot 1: Ground truth ─────────────────────────────────
ax = axes[0]
ax.plot(ground_truth[:, 0], ground_truth[:, 1], 'g-o',
        markersize=10, linewidth=2, label='Ground truth')

# Draw a closing line from last pose back to first (the perfect loop)
ax.plot([ground_truth[-1, 0], ground_truth[0, 0]],
        [ground_truth[-1, 1], ground_truth[0, 1]],
        'g--', linewidth=1, alpha=0.5)

# Label each pose
for i, pose in enumerate(ground_truth):
    ax.annotate(f'  {i}', (pose[0], pose[1]), fontsize=11, fontweight='bold')

ax.set_title('Ground Truth (Perfect Square)', fontsize=14, fontweight='bold')
ax.set_xlabel('X (meters)')
ax.set_ylabel('Y (meters)')
ax.grid(True, alpha=0.3)
ax.set_aspect('equal')
ax.legend()

# ─── Plot 2: Drifted trajectory ───────────────────────────
ax = axes[1]
ax.plot(ground_truth[:, 0], ground_truth[:, 1], 'g--o',
        markersize=8, linewidth=1, alpha=0.4, label='Ground truth')
ax.plot(drifted_poses[:, 0], drifted_poses[:, 1], 'r-o',
        markersize=10, linewidth=2, label='Drifted (VO only)')

# Draw the gap — the drift between last pose and where it should be
ax.annotate('', xy=(ground_truth[-1, 0], ground_truth[-1, 1]),
            xytext=(drifted_poses[-1, 0], drifted_poses[-1, 1]),
            arrowprops=dict(arrowstyle='<->', color='red', lw=2))
ax.text((ground_truth[-1, 0] + drifted_poses[-1, 0]) / 2 + 0.1,
        (ground_truth[-1, 1] + drifted_poses[-1, 1]) / 2,
        f'Drift: {np.sqrt(drift[0]**2 + drift[1]**2):.3f}m',
        color='red', fontsize=11, fontweight='bold')

for i, pose in enumerate(drifted_poses):
    ax.annotate(f'  {i}', (pose[0], pose[1]), fontsize=11,
                fontweight='bold', color='red')

ax.set_title('After VO (Drifted)', fontsize=14, fontweight='bold')
ax.set_xlabel('X (meters)')
ax.set_ylabel('Y (meters)')
ax.grid(True, alpha=0.3)
ax.set_aspect('equal')
ax.legend()

plt.tight_layout()
plt.show()

print("See the drift? Small errors every step → big error at the end.")
print("Pose 7 should be back near pose 0, but it's off.")

## ═══════════════════════════════════════════════════════════
## CELL 5: Define the Pose Graph Error Function
## ═══════════════════════════════════════════════════════════

def pose_graph_error(poses_flat, edges, loop_closures):
    """
    THE CORE OF POSE GRAPH OPTIMIZATION.

    This function computes the error for EVERY edge in the graph.
    The optimizer will call this repeatedly, adjusting poses_flat
    each time, trying to make these errors as small as possible.

    Think of it like this:
    - Each edge says "pose B should be HERE relative to pose A"
    - We check: "given where A and B actually are, is that true?"
    - The difference = error
    - Optimizer nudges poses until all differences are tiny

    It's like checking every spring in the network:
    - Measure how stretched each spring is (error)
    - Report all stretches to the optimizer
    - Optimizer adjusts ball positions to reduce total stretch

    poses_flat: all poses flattened into 1D array [x0,y0,θ0, x1,y1,θ1, ...]
    edges: list of (from_idx, to_idx, measurement, confidence)
    loop_closures: list of (from_idx, to_idx, measurement, confidence)
    """
    # Reshape flat array back into (N, 3) — each row is [x, y, theta]
    poses = poses_flat.reshape(-1, 3)
    errors = []

    # ─── VO Edge Errors ───────────────────────────────────
    for (i, j, measurement, confidence) in edges:
        # What the measurement PREDICTS: relative pose from i to j
        predicted = compute_relative_pose(poses[i], poses[j])

        # Error = difference between measurement and prediction
        err = (predicted - measurement) * confidence
        errors.extend(err)

    # ─── Loop Closure Edge Errors ─────────────────────────
    for (i, j, measurement, confidence) in loop_closures:
        predicted = compute_relative_pose(poses[i], poses[j])

        # Loop closure gets HIGHER confidence — we trust it
        # because it was verified with geometric matching
        err = (predicted - measurement) * confidence
        errors.extend(err)

    return np.array(errors)


# ─── Build the edge list ──────────────────────────────────
# VO edges: consecutive poses, moderate confidence
vo_confidence = 1.0    # baseline confidence for VO measurements

edges = []
for i in range(num_poses - 1):
    edges.append((i, i + 1, vo_measurements[i], vo_confidence))

print(f"VO edges: {len(edges)}")

# ─── Loop Closure Edge ────────────────────────────────────
# Pose 7 should be close to pose 0 (robot returned to start)
# This measurement says: "from pose 7, pose 0 is roughly HERE"
# We compute it from ground truth (simulating loop closure detection)
# and give it HIGH confidence — loop closure was geometrically verified

loop_measurement = compute_relative_pose(ground_truth[-1], ground_truth[0])

# Add small noise to loop closure too — it's not perfect either
loop_noise = np.random.randn(3) * noise_std * 0.5  # less noise than VO
loop_measurement_noisy = loop_measurement + loop_noise

# Loop closure gets 3x the confidence of VO edges
# WHY? It was verified with feature matching + RANSAC (like your Day 20)
# High inlier ratio = high confidence = stiff spring
loop_confidence = 3.0

loop_closures = [(num_poses - 1, 0, loop_measurement_noisy, loop_confidence)]

print(f"Loop closure edges: {len(loop_closures)} (pose {num_poses-1} → pose 0)")
print(f"Loop closure confidence: {loop_confidence}x (stiffer spring)")

## ═══════════════════════════════════════════════════════════
## CELL 6: Run the Optimizer!
## ═══════════════════════════════════════════════════════════

# Start with the drifted poses as initial guess
# The optimizer will adjust these to minimize total error
initial_guess = drifted_poses.copy().flatten()

# Pin pose 0 — don't let the optimizer move the starting position
# WHY? Without an anchor, the optimizer could slide the ENTIRE
# trajectory somewhere random and still have zero edge error.
# It's like solving a jigsaw puzzle — you need at least one piece
# fixed to the table. Pose 0 is our anchor.

def pose_graph_error_pinned(poses_flat, edges, loop_closures, anchor_pose):
    """
    Same as pose_graph_error but with an extra constraint:
    Pose 0 must stay at its original position.
    """
    errors = pose_graph_error(poses_flat, edges, loop_closures)

    # Anchor constraint: heavily penalize moving pose 0
    # confidence=10 makes this a very stiff spring
    poses = poses_flat.reshape(-1, 3)
    anchor_error = (poses[0] - anchor_pose) * 10.0
    errors = np.concatenate([errors, anchor_error])

    return errors


anchor = ground_truth[0]    # pin pose 0 to true start

# ─── RUN OPTIMIZATION ─────────────────────────────────────
# least_squares implements Levenberg-Marquardt algorithm
# (a variant of Gauss-Newton — the standard solver for pose graphs)
# It calls our error function repeatedly, adjusting poses each time,
# until the total error stops decreasing (converged to the valley)

print("Running pose graph optimization...")
print(f"Initial total error: {np.sum(pose_graph_error_pinned(initial_guess, edges, loop_closures, anchor)**2):.4f}")

result = least_squares(
    pose_graph_error_pinned,      # function that computes errors
    initial_guess,                # starting poses (drifted)
    args=(edges, loop_closures, anchor),  # extra arguments
    method='lm',                  # Levenberg-Marquardt (Gauss-Newton variant)
    verbose=0                     # quiet output
)

# Extract optimized poses
optimized_poses = result.x.reshape(-1, 3)

print(f"Final total error:   {np.sum(result.fun**2):.4f}")
print(f"Optimization converged: {result.success}")
print(f"Iterations: {result.nfev}")

# Show improvement
opt_drift = optimized_poses[-1] - ground_truth[-1]
print(f"\nBefore optimization — drift: {np.sqrt(drift[0]**2 + drift[1]**2):.3f}m")
print(f"After optimization  — drift: {np.sqrt(opt_drift[0]**2 + opt_drift[1]**2):.3f}m")

## ═══════════════════════════════════════════════════════════
## CELL 7: The Money Plot — Before vs After
## ═══════════════════════════════════════════════════════════

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# ─── Plot 1: Ground Truth ─────────────────────────────────
ax = axes[0]
ax.plot(ground_truth[:, 0], ground_truth[:, 1], 'g-o',
        markersize=10, linewidth=2, label='Ground truth')
ax.plot([ground_truth[-1, 0], ground_truth[0, 0]],
        [ground_truth[-1, 1], ground_truth[0, 1]],
        'g--', linewidth=1, alpha=0.5)
for i, pose in enumerate(ground_truth):
    ax.annotate(f'  {i}', (pose[0], pose[1]), fontsize=11, fontweight='bold')
ax.set_title('Ground Truth', fontsize=14, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True, alpha=0.3)
ax.set_aspect('equal')
ax.set_xlim(-0.5, 2.8)
ax.set_ylim(-2.8, 0.8)

# ─── Plot 2: Drifted (VO only) ───────────────────────────
ax = axes[1]
ax.plot(ground_truth[:, 0], ground_truth[:, 1], 'g--',
        linewidth=1, alpha=0.3, label='Ground truth')
ax.plot(drifted_poses[:, 0], drifted_poses[:, 1], 'r-o',
        markersize=10, linewidth=2, label='Drifted (VO only)')
for i, pose in enumerate(drifted_poses):
    ax.annotate(f'  {i}', (pose[0], pose[1]), fontsize=11,
                fontweight='bold', color='red')
ax.set_title('Before Optimization', fontsize=14, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True, alpha=0.3)
ax.set_aspect('equal')
ax.legend()
ax.set_xlim(-0.5, 2.8)
ax.set_ylim(-2.8, 0.8)

# ─── Plot 3: Optimized ───────────────────────────────────
ax = axes[2]
ax.plot(ground_truth[:, 0], ground_truth[:, 1], 'g--',
        linewidth=1, alpha=0.3, label='Ground truth')
ax.plot(drifted_poses[:, 0], drifted_poses[:, 1], 'r--',
        linewidth=1, alpha=0.3, label='Before optimization')
ax.plot(optimized_poses[:, 0], optimized_poses[:, 1], 'b-o',
        markersize=10, linewidth=2, label='After optimization')

# Draw loop closure edge
ax.plot([optimized_poses[-1, 0], optimized_poses[0, 0]],
        [optimized_poses[-1, 1], optimized_poses[0, 1]],
        'b--', linewidth=1.5, alpha=0.6)

for i, pose in enumerate(optimized_poses):
    ax.annotate(f'  {i}', (pose[0], pose[1]), fontsize=11,
                fontweight='bold', color='blue')
ax.set_title('After Optimization', fontsize=14, fontweight='bold')
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.grid(True, alpha=0.3)
ax.set_aspect('equal')
ax.legend()
ax.set_xlim(-0.5, 2.8)
ax.set_ylim(-2.8, 0.8)

plt.tight_layout()
plt.show()

# ─── Print per-pose corrections ──────────────────────────
print("\nPer-pose correction (how much each pose was moved):")
print(f"{'Pose':<6} {'X correction':>12} {'Y correction':>12} {'θ correction':>12}")
print("-" * 48)
for i in range(num_poses):
    dx = optimized_poses[i, 0] - drifted_poses[i, 0]
    dy = optimized_poses[i, 1] - drifted_poses[i, 1]
    dt = np.degrees(optimized_poses[i, 2] - drifted_poses[i, 2])
    print(f"  {i:<4} {dx:>+12.4f}m {dy:>+12.4f}m {dt:>+11.2f}°")

print("\nNotice: early poses barely moved, later poses moved MORE.")
print("The optimizer distributed the correction proportionally — NOT evenly!")
print("This is smarter than alpha-blending from Day 20.")

