# -*- coding: utf-8 -*-
"""Day33_SemenaticSegmentation_DeepLabV3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1up9BnBvnfMf7TF9L7aDY8TP4ymP46Thz
"""

import torch
import torchvision
from torchvision import transforms
import numpy as np
import cv2
import matplotlib.pyplot as plt
import urllib.request

# Download test image — street scene with multiple surfaces
urllib.request.urlretrieve("https://ultralytics.com/images/bus.jpg", "street.jpg")

# Load DeepLabV3 with ResNet101 backbone — pretrained on COCO
# WHY DeepLabV3: strong segmentation model, available in torchvision
# WHY ResNet101: deep backbone that captures fine details
# WHY pretrained: learned to segment 21 classes from COCO dataset
model = torchvision.models.segmentation.deeplabv3_resnet101(
    weights=torchvision.models.segmentation.DeepLabV3_ResNet101_Weights.DEFAULT
)
model.eval()
# WHY eval(): same as MiDaS — disables training behavior
# Dropout and batch norm behave differently during inference

# The 21 PASCAL VOC classes this model knows
CLASSES = [
    'background', 'aeroplane', 'bicycle', 'bird', 'boat',
    'bottle', 'bus', 'car', 'cat', 'chair',
    'cow', 'dining table', 'dog', 'horse', 'motorbike',
    'person', 'potted plant', 'sheep', 'sofa', 'train', 'tv/monitor'
]

# Color map — one distinct color per class for visualization
# WHY specific colors: each class needs a visually distinct color
# so you can immediately see what the model segmented
COLORS = np.array([
    [0,0,0],       [128,0,0],     [0,128,0],     [128,128,0],   [0,0,128],
    [128,0,128],   [0,128,128],   [128,128,128],  [64,0,0],      [192,0,0],
    [64,128,0],    [192,128,0],   [64,0,128],     [192,0,128],   [64,128,128],
    [192,128,128], [0,64,0],      [128,64,0],     [0,192,0],     [128,192,0],
    [0,64,128]
], dtype=np.uint8)

print(f"Model loaded: DeepLabV3-ResNet101")
print(f"Classes: {len(CLASSES)}")
print(f"Parameters: {sum(p.numel() for p in model.parameters()):,}")
for i, c in enumerate(CLASSES):
    print(f"  {i:2d}: {c}")

# Load and preprocess the image
img = cv2.imread("street.jpg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# DeepLabV3 expects specific preprocessing
# WHY these exact values: the model was TRAINED with this normalization
# If you feed unnormalized images, outputs are garbage
# Same reason you can't feed BGR to an RGB-trained model
preprocess = transforms.Compose([
    transforms.ToTensor(),
    # WHY ToTensor: converts (H,W,3) uint8 numpy → (3,H,W) float [0,1]
    # PyTorch models expect (channels, height, width) not (height, width, channels)
    # Also scales 0-255 → 0.0-1.0

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
    # WHY these specific numbers: ImageNet dataset statistics
    # Every model trained on ImageNet uses these EXACT values
    # It centers the data around zero with unit variance
    # Like Z-score normalization in statistics
])

input_tensor = preprocess(img_rgb).unsqueeze(0)
# WHY unsqueeze(0): adds batch dimension
# Model expects (batch, channels, height, width)
# One image = batch size 1 → (1, 3, 1080, 810)

print(f"Input shape: {input_tensor.shape}")

# Run segmentation
with torch.no_grad():
    output = model(input_tensor)
# output is a dict with 'out' key containing the predictions

# Get class predictions for each pixel
# output['out'] shape: (1, 21, H, W) — 21 scores per pixel
# argmax picks the highest-scoring class for each pixel
seg_map = output['out'][0].argmax(dim=0).numpy()
# WHY argmax(dim=0): for each pixel, which of the 21 classes scored highest?
# WHY [0]: remove batch dimension
# WHY .numpy(): convert to NumPy for visualization

print(f"Segmentation map shape: {seg_map.shape}")
print(f"Unique classes found: {np.unique(seg_map)}")
print(f"Class names found:")
for cls_id in np.unique(seg_map):
    pixel_count = np.sum(seg_map == cls_id)
    percentage = pixel_count / seg_map.size * 100
    print(f"  {CLASSES[cls_id]:<15} — {pixel_count:>6} pixels ({percentage:.1f}%)")

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Original image
axes[0].imshow(img_rgb)
axes[0].set_title('Original image', fontsize=14)
axes[0].axis('off')

# Segmentation map — color coded
# Convert class IDs to colors using our color map
seg_colored = COLORS[seg_map]
# WHY COLORS[seg_map]: NumPy fancy indexing
# seg_map has values 0, 6, 15 at each pixel
# COLORS[0] = black (background)
# COLORS[6] = [0,128,128] teal (bus)
# COLORS[15] = [192,128,128] pink (person)
# This replaces a for loop over 874,800 pixels — instant

axes[1].imshow(seg_colored)
axes[1].set_title('Segmentation map', fontsize=14)
axes[1].axis('off')

# Overlay — segmentation blended on original image
overlay = img_rgb.copy()
mask = seg_map > 0    # non-background pixels
# WHY mask > 0: only colorize pixels that have a class
# Background stays as original image

overlay[mask] = (0.4 * img_rgb[mask] + 0.6 * seg_colored[mask]).astype(np.uint8)
# WHY 0.4/0.6 blend: see original image through the color tint
# 0.6 weight on segmentation makes classes clearly visible
# 0.4 weight on original preserves enough detail to see what's there

axes[2].imshow(overlay)
axes[2].set_title('Segmentation overlay', fontsize=14)
axes[2].axis('off')

# Add legend
legend_text = ""
for cls_id in np.unique(seg_map):
    count = np.sum(seg_map == cls_id)
    pct = count / seg_map.size * 100
    legend_text += f"{CLASSES[cls_id]}: {pct:.1f}%  "
plt.suptitle(legend_text, fontsize=12, y=0.02)

plt.tight_layout()
plt.show()

print("Notice: segmentation follows the EXACT contour of each person")
print("YOLO would just draw a rectangle around them")
print("The bus mask covers exactly the bus pixels — not sky, not road")

# ─── Semantic Point Cloud ──────────────────────────────────
# Combine segmentation + depth (from MiDaS Day 32) + RGB
# Each 3D point knows: WHERE it is (XYZ), WHAT COLOR it is (RGB),
# and WHAT CLASS it is (person, bus, background)

# Reuse MiDaS depth from Day 32 — or re-run it here
# Load MiDaS
midas = torch.hub.load("intel-isl/MiDaS", "MiDaS_small")
midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
midas_transform = midas_transforms.small_transform
midas.eval()

# Run MiDaS on same image
with torch.no_grad():
    midas_input = midas_transform(img_rgb)
    depth_pred = midas(midas_input)
    depth_pred = torch.nn.functional.interpolate(
        depth_pred.unsqueeze(1),
        size=img_rgb.shape[:2],
        mode="bicubic",
        align_corners=False,
    ).squeeze().numpy()

# Normalize depth to reasonable range (0.5m to 20m)
# WHY normalize: MiDaS gives relative depth (12 to 913)
# We scale it to approximate real-world meters
# Higher MiDaS value = CLOSER, so we INVERT
# Then scale to a reasonable range
depth_inv = depth_pred.max() - depth_pred  # invert: close→small, far→large
depth_meters = 0.5 + (depth_inv / depth_inv.max()) * 19.5
# WHY invert: MiDaS gives HIGH values for close objects
# But in 3D, close objects have SMALL Z values
# After inversion and scaling: range is 0.5m to 20m

# Back-project to 3D using Day 8 formula
# Using approximate intrinsics for this image
h, w = img_rgb.shape[:2]
fx = fy = w * 1.0    # approximate focal length
cx, cy = w / 2, h / 2

u, v = np.meshgrid(range(w), range(h))
# WHY meshgrid: creates grid of ALL pixel coordinates at once
# u = column index (0 to 809), v = row index (0 to 1079)

Z = depth_meters
X = (u - cx) * Z / fx   # Day 8 formula: X = (u - cx) * Z / fx
Y = (v - cy) * Z / fy   # Day 8 formula: Y = (v - cy) * Z / fy

# Stack into (H, W, 3) then flatten to (N, 3)
points_3d = np.stack([X, Y, Z], axis=-1).reshape(-1, 3)
colors = img_rgb.reshape(-1, 3) / 255.0   # normalize colors to 0-1
labels = seg_map.reshape(-1)               # class label per point
# WHY reshape(-1, 3): flatten from 2D image grid to list of points
# WHY /255.0: Open3D expects colors in [0, 1] range

print(f"Total points: {len(points_3d):,}")
print(f"Points per class:")
for cls_id in np.unique(labels):
    count = np.sum(labels == cls_id)
    print(f"  {CLASSES[cls_id]:<15}: {count:,} points")

# ─── Visualize semantic point cloud ────────────────────────
# Three views: colored by RGB, colored by class, filtered by class

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Downsample for plotting (874K points is too many for matplotlib)
step = 8   # take every 8th point
# WHY downsample: matplotlib can't handle 874K scatter points
# Open3D could, but we're in Colab without display
idx = np.arange(0, len(points_3d), step)

pts = points_3d[idx]
cols = colors[idx]
lbls = labels[idx]

# ─── Plot 1: RGB colored point cloud (like Day 22) ────────
ax = axes[0]
ax.scatter(pts[:, 0], -pts[:, 1], c=cols, s=0.1)
# WHY -pts[:,1]: flip Y so image looks right-side up
# In camera coords, Y points DOWN. Negate to point UP.
ax.set_title('RGB colored (Day 22 style)', fontsize=14)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_aspect('equal')

# ─── Plot 2: Class colored (semantic) ─────────────────────
ax = axes[1]
class_colors = COLORS[lbls] / 255.0
# WHY COLORS[lbls]: same fancy indexing trick from visualization
# Each point colored by its class: teal=bus, pink=person, black=bg
ax.scatter(pts[:, 0], -pts[:, 1], c=class_colors, s=0.1)
ax.set_title('Semantic colored (NEW!)', fontsize=14)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_aspect('equal')

# ─── Plot 3: Person points ONLY — extracted by class ──────
ax = axes[2]
person_mask = lbls == 15   # class 15 = person
# WHY == 15: CLASSES[15] = 'person'
# This boolean mask selects ONLY person points
# A robot could use this to know exactly where people are in 3D

person_pts = pts[person_mask]
person_cols = cols[person_mask]

bus_mask = lbls == 6       # class 6 = bus
bus_pts = pts[bus_mask]

ax.scatter(person_pts[:, 0], -person_pts[:, 1], c='red', s=0.3, label=f'Person ({np.sum(person_mask):,} pts)')
ax.scatter(bus_pts[:, 0], -bus_pts[:, 1], c='cyan', s=0.1, alpha=0.3, label=f'Bus ({np.sum(bus_mask):,} pts)')
ax.set_title('Filtered: person (red) + bus (cyan)', fontsize=14)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.legend(fontsize=10, markerscale=10)
ax.set_aspect('equal')

plt.tight_layout()
plt.show()

# ─── The power: query 3D space by class ───────────────────
print("\n3D bounding box per class:")
for cls_id in [6, 15]:  # bus, person
    mask = labels == cls_id
    cls_points = points_3d[mask]
    print(f"\n  {CLASSES[cls_id]}:")
    print(f"    X range: {cls_points[:,0].min():.2f}m to {cls_points[:,0].max():.2f}m")
    print(f"    Y range: {cls_points[:,1].min():.2f}m to {cls_points[:,1].max():.2f}m")
    print(f"    Z range: {cls_points[:,2].min():.2f}m to {cls_points[:,2].max():.2f}m (depth)")
    print(f"    Closest point: {cls_points[:,2].min():.2f}m from camera")

# ═══════════════════════════════════════════════════════════
# POINT CLOUD PROCESSING — what you do AFTER creating the cloud
# ═══════════════════════════════════════════════════════════

# ─── 1. Voxel Downsampling (you did this Day 21) ──────────
# Reduce density while preserving shape
# 874K points is too many for real-time processing
# Downsample to ~1 point per 10cm cube

voxel_size = 0.3  # 30cm voxels
# WHY 0.3m: coarse enough to dramatically reduce points
# Fine enough to preserve human body shape

def voxel_downsample(points, colors, labels, voxel_size):
    """
    Keep one point per voxel (3D cube).
    Same concept as Day 21 Open3D voxel_down_sample,
    but implemented from scratch so you understand it.

    Analogy: imagine dividing 3D space into a grid of cubes.
    If 50 points fall in the same cube, keep only one
    (the average of all 50). Dramatically reduces point count
    while preserving overall shape.
    """
    # Quantize points to voxel grid
    # WHY floor divide: snaps each point to its voxel corner
    # Points at (0.12, 0.34, 0.56) and (0.18, 0.29, 0.51)
    # both snap to (0, 0, 0) with voxel_size=0.3 → same voxel
    voxel_indices = np.floor(points / voxel_size).astype(int)

    # Create unique key for each voxel
    # WHY string key: easy way to hash 3D coordinates
    voxel_dict = {}
    for i in range(len(points)):
        key = tuple(voxel_indices[i])
        if key not in voxel_dict:
            voxel_dict[key] = {'pts': [], 'cols': [], 'lbls': []}
        voxel_dict[key]['pts'].append(points[i])
        voxel_dict[key]['cols'].append(colors[i])
        voxel_dict[key]['lbls'].append(labels[i])

    # Average points within each voxel, majority vote for label
    down_pts, down_cols, down_lbls = [], [], []
    for key, data in voxel_dict.items():
        down_pts.append(np.mean(data['pts'], axis=0))
        down_cols.append(np.mean(data['cols'], axis=0))
        # WHY mean for position/color: smooth average
        # WHY majority vote for label: a voxel on the boundary
        # might have 8 person pixels and 2 bus pixels → label = person
        unique, counts = np.unique(data['lbls'], return_counts=True)
        down_lbls.append(unique[np.argmax(counts)])

    return np.array(down_pts), np.array(down_cols), np.array(down_lbls)

pts_down, cols_down, lbls_down = voxel_downsample(
    points_3d, colors, labels, voxel_size)

print(f"Before downsampling: {len(points_3d):,} points")
print(f"After downsampling:  {len(pts_down):,} points")
print(f"Reduction: {len(points_3d)/len(pts_down):.0f}x fewer points")
print(f"Per class after downsample:")
for cls_id in np.unique(lbls_down):
    count = np.sum(lbls_down == cls_id)
    print(f"  {CLASSES[cls_id]:<15}: {count:,} points")

# ─── 2. Statistical Outlier Removal ───────────────────────
# Remove noisy points that are far from their neighbors

def remove_outliers(points, colors, labels, k=20, std_ratio=2.0):
    """
    For each point, compute mean distance to its K nearest neighbors.
    If a point's mean neighbor distance is more than std_ratio
    standard deviations above the global mean → it's an outlier.

    Analogy: in a crowd, most people stand near others.
    Someone standing 50 meters from everyone else is suspicious
    (probably a noisy measurement). Remove them.

    k=20: check 20 nearest neighbors
    std_ratio=2.0: remove if > 2 standard deviations from mean
    """
    from scipy.spatial import KDTree

    # Build KD-tree for fast nearest neighbor search
    # WHY KDTree: finding K nearest neighbors in 874K points
    # Brute force is O(N^2). KDTree is O(N log N).
    tree = KDTree(points)

    # For each point, find distance to K nearest neighbors
    distances, _ = tree.query(points, k=k+1)
    # WHY k+1: the closest "neighbor" is the point itself (distance=0)
    # Skip the first column (self-distance)
    mean_distances = distances[:, 1:].mean(axis=1)
    # WHY mean of K distances: summarizes how "lonely" each point is

    # Global statistics
    global_mean = mean_distances.mean()
    global_std = mean_distances.std()

    # Keep points within threshold
    threshold = global_mean + std_ratio * global_std
    inlier_mask = mean_distances < threshold
    # WHY this threshold: points with neighbors much farther than average
    # are probably noise. 2 standard deviations catches ~5% outliers.

    return points[inlier_mask], colors[inlier_mask], labels[inlier_mask], inlier_mask

pts_clean, cols_clean, lbls_clean, kept = remove_outliers(
    pts_down, cols_down, lbls_down, k=10, std_ratio=1.5)

print(f"\nBefore outlier removal: {len(pts_down):,} points")
print(f"After outlier removal:  {len(pts_clean):,} points")
print(f"Removed: {len(pts_down) - len(pts_clean):,} outliers")

# ─── 3. Ground Plane Extraction ───────────────────────────
# Find which points are "floor" — critical for navigation

def extract_ground_plane(points, labels, y_threshold=0.5):
    """
    Simple ground extraction: points with Y > threshold
    (remember Y points DOWN in camera coordinates, so large Y = low)

    More sophisticated: RANSAC plane fitting (like findEssentialMat
    but for planes instead of epipolar geometry)

    For navigation: ground points = driveable area
    Non-ground points = obstacles
    """
    # In our coordinate system, ground is at large Y values
    # (camera Y-axis points downward)
    y_values = points[:, 1]
    y_median = np.median(y_values)

    ground_mask = y_values > (y_median + y_threshold)
    obstacle_mask = ~ground_mask

    return ground_mask, obstacle_mask

ground_mask, obstacle_mask = extract_ground_plane(pts_clean, lbls_clean)
print(f"\nGround plane extraction:")
print(f"  Ground points:   {np.sum(ground_mask):,}")
print(f"  Obstacle points: {np.sum(obstacle_mask):,}")

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# ─── Plot 1: Downsampled semantic cloud ────────────────────
ax = axes[0]
class_cols = COLORS[lbls_clean.astype(int)] / 255.0
ax.scatter(pts_clean[:, 0], -pts_clean[:, 1], c=class_cols, s=2)
ax.set_title(f'Downsampled + cleaned ({len(pts_clean):,} pts)', fontsize=13)
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.set_aspect('equal')

# ─── Plot 2: Ground vs obstacles ──────────────────────────
ax = axes[1]
ax.scatter(pts_clean[ground_mask, 0], -pts_clean[ground_mask, 1],
           c='green', s=3, label=f'Ground ({np.sum(ground_mask):,})')
ax.scatter(pts_clean[obstacle_mask, 0], -pts_clean[obstacle_mask, 1],
           c='red', s=3, label=f'Obstacle ({np.sum(obstacle_mask):,})')
ax.set_title('Ground (green) vs obstacles (red)', fontsize=13)
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.legend(fontsize=10, markerscale=5)
ax.set_aspect('equal')

# ─── Plot 3: Obstacle breakdown by class ──────────────────
ax = axes[2]
obstacle_pts = pts_clean[obstacle_mask]
obstacle_lbls = lbls_clean[obstacle_mask]

for cls_id in np.unique(obstacle_lbls):
    cls_mask = obstacle_lbls == cls_id
    cls_pts = obstacle_pts[cls_mask]
    count = np.sum(cls_mask)
    if count > 10:
        ax.scatter(cls_pts[:, 0], -cls_pts[:, 1], s=3,
                   label=f'{CLASSES[int(cls_id)]} ({count:,})')

ax.set_title('Obstacles by class', fontsize=13)
ax.set_xlabel('X (m)')
ax.set_ylabel('Y (m)')
ax.legend(fontsize=10, markerscale=5)
ax.set_aspect('equal')

plt.tight_layout()
plt.show()

# ─── Final summary: what a robot knows from ONE image ─────
print("=" * 60)
print("FROM ONE RGB IMAGE, THE ROBOT NOW KNOWS:")
print("=" * 60)
print(f"\n1. WHAT is in the scene:")
for cls_id in np.unique(lbls_clean):
    count = np.sum(lbls_clean == cls_id)
    print(f"   - {CLASSES[int(cls_id)]}: {count:,} 3D points")

print(f"\n2. WHERE each object is in 3D:")
for cls_id in [6, 15]:
    mask = lbls_clean == cls_id
    if np.sum(mask) > 0:
        cls_pts = pts_clean[mask]
        print(f"   - {CLASSES[cls_id]}: closest at {cls_pts[:,2].min():.1f}m, "
              f"farthest at {cls_pts[:,2].max():.1f}m")

print(f"\n3. WHERE the robot can drive:")
print(f"   - {np.sum(ground_mask):,} ground points (safe)")
print(f"   - {np.sum(obstacle_mask):,} obstacle points (avoid)")

print(f"\n4. COMPLETE PIPELINE (one frame):")
print(f"   RGB image (810x1080)")
print(f"   -> DeepLabV3: semantic segmentation (21 classes)")
print(f"   -> MiDaS: depth estimation (relative)")
print(f"   -> Back-projection: 874,800 3D points")
print(f"   -> Voxel downsample: 6,079 points (144x reduction)")
print(f"   -> Outlier removal: 5,751 clean points")
print(f"   -> Ground extraction: drive vs avoid")
print(f"   Total: one image -> complete 3D scene understanding")

print("\n" + "=" * 60)
print("METHODS COMPARISON — YOUR COMPLETE PERCEPTION TOOLKIT")
print("=" * 60)
print(f"{'Method':<25} {'What it gives':<30} {'Day'}")
print("-" * 70)
print(f"{'ORB features':<25} {'WHERE are points (no ID)':<30} {'13'}")
print(f"{'YOLO detection':<25} {'WHAT objects + rough boxes':<30} {'30'}")
print(f"{'Semantic segmentation':<25} {'WHAT is every pixel':<30} {'33'}")
print(f"{'Stereo depth':<25} {'HOW FAR (absolute meters)':<30} {'9-12'}")
print(f"{'MiDaS depth':<25} {'HOW FAR (relative ordering)':<30} {'32'}")
print(f"{'RGB-D point cloud':<25} {'3D position + color':<30} {'22'}")
print(f"{'Semantic point cloud':<25} {'3D position + color + class':<30} {'33'}")
print(f"{'EKF fusion':<25} {'WHERE AM I (VO + IMU fused)':<30} {'32'}")
print(f"{'Pose graph optimization':<25} {'CORRECT trajectory drift':<30} {'29'}")
print(f"{'Vocabulary tree':<25} {'BEEN HERE BEFORE? (fast)':<30} {'31'}")


