# -*- coding: utf-8 -*-
"""Day32_MiDAS_DepthAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cCYmU8M1fdg1Gfwd1A6gvIm2cM60lgz

Using MiDAS by INTEL to analysis depth and image data
"""

import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt
import urllib.request

# Use the same test image from YOLO day — has people close, bus far
urllib.request.urlretrieve("https://ultralytics.com/images/bus.jpg", "street.jpg")

# Load MiDaS small model
model_type = "MiDaS_small"
midas = torch.hub.load("intel-isl/MiDaS", model_type)

midas_transforms = torch.hub.load("intel-isl/MiDaS", "transforms")
transform = midas_transforms.small_transform

midas.eval()

print(f"Model loaded: {model_type}")
print(f"Model parameters: {sum(p.numel() for p in midas.parameters()):,}")

# Load the image
img = cv2.imread("street.jpg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
# WHY BGR2RGB: MiDaS expects RGB (trained on RGB data)
# Same trap from Day 7 — OpenCV loads BGR, everything else expects RGB

# Apply the transform — resizes and normalizes for MiDaS
input_batch = transform(img_rgb)
# WHY transform: MiDaS_small expects 256x256 input, normalized
# The transform handles this automatically
# Similar to how YOLO internally resizes to 640x640

# Run inference — predict depth
with torch.no_grad():
    # WHY no_grad: we're not training, just predicting
    # Skips gradient computation — 2x faster, less memory
    prediction = midas(input_batch)

    # Resize prediction back to original image size
    prediction = torch.nn.functional.interpolate(
        prediction.unsqueeze(1),          # add channel dimension
        size=img_rgb.shape[:2],           # original height, width
        mode="bicubic",                   # smooth upsampling
        align_corners=False,
    ).squeeze()
    # WHY interpolate: MiDaS outputs at 256x256
    # We want depth map at same resolution as input image
    # bicubic = smooth scaling (no blocky pixels)

depth_map = prediction.numpy()
# WHY .numpy(): convert from PyTorch tensor to NumPy array
# Now it's a regular 2D array we can visualize and process

print(f"Input image shape: {img_rgb.shape}")
print(f"Depth map shape: {depth_map.shape}")
print(f"Depth range: {depth_map.min():.1f} to {depth_map.max():.1f}")
print(f"NOTE: MiDaS outputs RELATIVE depth (not meters)")
print(f"Higher value = CLOSER to camera")

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# Original image
axes[0].imshow(img_rgb)
axes[0].set_title('Original image', fontsize=14)
axes[0].axis('off')

# Depth map — hot colormap (red = close, blue = far)
im = axes[1].imshow(depth_map, cmap='inferno')
axes[1].set_title('MiDaS depth map (bright = close)', fontsize=14)
axes[1].axis('off')
plt.colorbar(im, ax=axes[1], shrink=0.8, label='Relative depth')

# Depth map overlaid on original — see which objects are close/far
axes[2].imshow(img_rgb, alpha=0.4)
axes[2].imshow(depth_map, cmap='inferno', alpha=0.6)
axes[2].set_title('Depth overlaid on image', fontsize=14)
axes[2].axis('off')

plt.tight_layout()
plt.show()

# Print depth values at specific locations
h, w = depth_map.shape
print(f"\nDepth at specific points:")
print(f"  Center person (540, 150):    {depth_map[540, 150]:.1f} (should be HIGH — close)")
print(f"  Bus body (400, 500):         {depth_map[400, 500]:.1f} (should be MEDIUM — behind people)")
print(f"  Sky/background (100, 400):   {depth_map[100, 400]:.1f} (should be LOW — far away)")
print(f"  Ground near camera (900, 400): {depth_map[900, 400]:.1f} (should be HIGH — close)")

# ─── How monocular depth connects to your VO pipeline ─────
#
# Problem: VO gives |t| = 1 (scale ambiguity)
# Solution: Use depth map to estimate actual scale
#
# Method:
# 1. Triangulate 3D points from two frames (you did this Day 16)
# 2. Those points have UNKNOWN scale (arbitrary units)
# 3. Estimate depth of same points using MiDaS
# 4. Compare: ratio = MiDaS_depth / triangulated_depth
# 5. Multiply t by that ratio → scaled translation
#
# This doesn't give PERFECT metric scale (MiDaS is relative)
# but it makes the scale CONSISTENT across the trajectory

# Simulate this with our bus image
# Pick some points at different depths
points = [
    ("Person (close)", 540, 150, 2.0),     # ~2m away in reality
    ("Bus (medium)",   400, 500, 5.0),     # ~5m away
    ("Building (far)", 200, 600, 20.0),    # ~20m away
]

print("Monocular depth → scale recovery concept:")
print("=" * 60)
print(f"{'Object':<20} {'MiDaS depth':>12} {'Real depth':>12} {'Ratio':>8}")
print("-" * 60)

ratios = []
for name, row, col, real_depth in points:
    midas_depth = depth_map[row, col]
    ratio = real_depth / midas_depth
    ratios.append(ratio)
    print(f"{name:<20} {midas_depth:>12.1f} {real_depth:>10.1f}m {ratio:>8.4f}")

avg_ratio = np.mean(ratios)
print(f"\nAverage scale factor: {avg_ratio:.4f}")
print(f"Multiply ALL MiDaS values by {avg_ratio:.4f} to get approximate meters")
print(f"\nVerification:")
for name, row, col, real_depth in points:
    estimated = depth_map[row, col] * avg_ratio
    error = abs(estimated - real_depth)
    print(f"  {name}: MiDaS says {depth_map[row,col]:.0f} × {avg_ratio:.4f} = {estimated:.1f}m (true: {real_depth}m, error: {error:.1f}m)")

# ─── Connection to your ROS2 pipeline ─────────────────────
print("\n" + "=" * 60)
print("HOW THIS FITS IN YOUR ROS2 PIPELINE:")
print("=" * 60)
print("""
Option A: MiDaS as a separate ROS2 node
  camera → /camera/image_raw → midas_node → /depth/estimated
  vo_node subscribes to /depth/estimated for scale correction

Option B: Integrate into vo_node directly
  Each frame: run VO for direction, run MiDaS for depth scale
  Combine: scaled_t = t_direction * midas_scale_factor

Either way, the VO trajectory gets metric scale without
a depth sensor or stereo camera. Just one RGB camera.

Limitations:
  - MiDaS gives RELATIVE depth, not absolute meters
  - Need at least one known measurement to calibrate
  - Less accurate than stereo or LiDAR
  - Slower than hardware depth sensors
  - But works with ANY camera — phone, drone, dashcam
""")

# ─── Compare all depth methods you've learned ─────────────
print("=" * 60)
print("DEPTH ESTIMATION METHODS — YOUR COMPLETE TOOLKIT")
print("=" * 60)

methods = [
    ["Method",            "Input",           "Output",         "Scale?",  "Day"],
    ["Stereo disparity",  "Two cameras",     "Absolute depth", "Yes",     "9-12"],
    ["SfM triangulation", "Multiple views",  "Relative depth", "No",      "16-17"],
    ["RGB-D sensor",      "Depth camera",    "Absolute depth", "Yes",     "22"],
    ["Monocular DL",      "Single RGB",      "Relative depth", "No*",     "32"],
    ["VO + IMU (EKF)",    "Camera + IMU",    "Scaled trajectory", "Partial", "32"],
]

for row in methods:
    print(f"  {row[0]:<20} {row[1]:<18} {row[2]:<18} {row[3]:<8} Day {row[4]}")

print("\n* Monocular depth can be calibrated to metric with one known measurement")

