# -*- coding: utf-8 -*-
"""Day30 YOLO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezi7uKvKvTGNbVJQlRYIHyf3cmjk6l0P
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Load pretrained YOLOv8 nano model
# "nano" = smallest, fastest version — good for real-time on robots
# Already trained on COCO dataset (80 object classes)
model = YOLO('yolov8n.pt')

print(f"Model loaded: YOLOv8 Nano")
print(f"Number of classes: {len(model.names)}")
print(f"Classes: {list(model.names.values())[:10]}...")  # first 10

# Download a test image with objects in it
import urllib.request

url = "https://ultralytics.com/images/bus.jpg"
urllib.request.urlretrieve(url, "test.jpg")

# Run YOLO on the image
results = model("test.jpg")

# Get the first result (we only sent one image)
result = results[0]

# What did it find?
print(f"Detections: {len(result.boxes)}")
print()
for box in result.boxes:
    class_id = int(box.cls[0])           # which class (0-79)
    class_name = model.names[class_id]   # "person", "bus", etc.
    confidence = float(box.conf[0])      # 0.0 to 1.0
    x1, y1, x2, y2 = box.xyxy[0]        # bounding box corners

    print(f"  {class_name:<12} conf: {confidence:.2f}  "
          f"box: ({int(x1)}, {int(y1)}) → ({int(x2)}, {int(y2)})")

# Draw the detections on the image
img = cv2.imread("test.jpg")
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

# Get the annotated image — YOLO draws boxes for us
annotated = result.plot()
annotated_rgb = cv2.cvtColor(annotated, cv2.COLOR_BGR2RGB)

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].imshow(img_rgb)
axes[0].set_title("Original", fontsize=14)
axes[0].axis('off')

axes[1].imshow(annotated_rgb)
axes[1].set_title(f"YOLO Detections ({len(result.boxes)} objects)", fontsize=14)
axes[1].axis('off')

plt.tight_layout()
plt.show()

