# -*- coding: utf-8 -*-
"""Day32_EKF_2D.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r8eAijGrgoVhqc_iu6zYrx27LyRP67Ey
"""

import numpy as np
import matplotlib.pyplot as plt

# ─── Simulate a robot driving in a circle ─────────────────
# Ground truth: robot drives in a circle of radius 5m
# Total time: 20 seconds, 200 steps (10 Hz)

dt = 0.1           # 100ms between steps (10 Hz)
n_steps = 200      # 20 seconds of driving
radius = 5.0       # circle radius in meters
omega = 2 * np.pi / 20  # angular velocity (one full circle in 20s)

# Generate ground truth trajectory
t = np.arange(n_steps) * dt
true_x = radius * np.cos(omega * t)       # circular path X
true_y = radius * np.sin(omega * t)       # circular path Y
true_theta = omega * t + np.pi/2          # heading angle (tangent to circle)

# Ground truth velocity and angular velocity
true_v = radius * omega                    # constant speed along circle
true_omega_z = omega                       # constant turn rate

print(f"Simulated robot: radius={radius}m, speed={true_v:.2f}m/s")
print(f"Duration: {n_steps*dt:.0f}s, steps: {n_steps}")
print(f"One full circle in {2*np.pi/omega:.0f}s")

# ─── Simulate IMU measurements (noisy) ────────────────────
# IMU gives: linear velocity + angular velocity (simplified)
# Real IMU gives acceleration, but we simplify to velocity for clarity

imu_v_noise = 0.3       # velocity noise std (m/s)
imu_omega_noise = 0.05  # angular velocity noise std (rad/s)

imu_v = true_v + np.random.randn(n_steps) * imu_v_noise
# WHY add noise: real IMU measurements are never perfect
# Each measurement is slightly off — these errors accumulate

imu_omega = true_omega_z + np.random.randn(n_steps) * imu_omega_noise

# ─── Simulate VO measurements (noisy, with gaps) ──────────
# VO gives: position (x, y) — but sometimes FAILS (no features)

vo_x_noise = 0.5        # position noise std (meters)
vo_y_noise = 0.5

# VO fails in certain regions (simulating textureless hallway)
# Frames 60-100: camera goes blind (no features)
vo_available = np.ones(n_steps, dtype=bool)
vo_available[60:100] = False    # 4 seconds of blindness
# WHY: this simulates a textureless hallway or dark region
# During this gap, only IMU is available — EKF must survive on predictions alone

vo_x = true_x + np.random.randn(n_steps) * vo_x_noise
vo_y = true_y + np.random.randn(n_steps) * vo_y_noise

print(f"\nIMU noise: velocity={imu_v_noise}m/s, rotation={np.degrees(imu_omega_noise):.1f}deg/s")
print(f"VO noise: position={vo_x_noise}m")
print(f"VO blackout: frames 60-100 (steps {60}-{100}, t={60*dt:.1f}s-{100*dt:.1f}s)")
print(f"During blackout: EKF runs on IMU prediction ONLY")

class EKF:
    """
    Extended Kalman Filter for fusing IMU + Visual Odometry.

    State: [x, y, theta] — position and heading
    Predict: uses IMU (velocity + angular velocity) to guess next state
    Update: uses VO (position measurement) to correct the guess

    The "Extended" in EKF means it handles NONLINEAR motion models.
    Basic Kalman Filter only works for linear systems.
    A robot turning in a circle is nonlinear (sin/cos in the motion model),
    so we need the Extended version which linearizes at each step.
    """

    def __init__(self, x0, y0, theta0):
        # ─── STATE VECTOR ─────────────────────────────────
        # What the robot believes about itself right now
        # [x, y, theta] — 2D position + heading angle
        self.state = np.array([x0, y0, theta0])

        # ─── COVARIANCE MATRIX P ──────────────────────────
        # 3x3 matrix — how UNCERTAIN each state variable is
        # Diagonal = variance of each variable independently
        # Off-diagonal = how uncertainties are correlated
        # Starts small: we know where we are at the beginning
        self.P = np.eye(3) * 0.1
        # WHY 0.1: slightly uncertain at start, not zero
        # Zero would mean "I'm PERFECTLY sure" which is never true
        # np.eye(3) = identity matrix = no correlation between x, y, theta

        # ─── PROCESS NOISE Q ──────────────────────────────
        # How much uncertainty the IMU ADDS each prediction step
        # Bigger Q = "I don't trust my IMU much"
        # Smaller Q = "My IMU is very accurate"
        self.Q = np.diag([0.1, 0.1, 0.01])
        # WHY these values: x,y get 0.1 noise (position uncertain)
        # theta gets 0.01 (gyroscope is fairly accurate for heading)
        # WHY diagonal: assumes x noise, y noise, theta noise
        # are independent (simplification)

        # ─── MEASUREMENT NOISE R ──────────────────────────
        # How much we trust the camera/VO measurement
        # Bigger R = "VO is noisy, don't trust it much"
        # Smaller R = "VO is very accurate, trust it a lot"
        self.R = np.diag([0.5, 0.5])
        # WHY 0.5: matches our VO noise std of 0.5m
        # WHY 2x2 not 3x3: VO only measures [x, y], not theta
        # So measurement noise is 2D, not 3D

    def predict(self, v, omega, dt):
        """
        PREDICT STEP — use IMU to project state forward in time.

        "Based on my current velocity and turn rate,
        where SHOULD I be after dt seconds?"

        This is like dead reckoning: I was HERE, I moved THIS much,
        so I should be THERE. But my motion estimate is noisy,
        so my uncertainty GROWS.
        """
        x, y, theta = self.state

        # ─── State prediction (motion model) ──────────────
        # Move forward by v*dt in the direction of current heading theta
        # Turn by omega*dt
        x_new = x + v * np.cos(theta) * dt
        y_new = y + v * np.sin(theta) * dt
        theta_new = theta + omega * dt
        # WHY cos/sin: velocity is along heading direction
        # If theta=0 (facing right), cos=1 sin=0 → move in +x
        # If theta=90° (facing up), cos=0 sin=1 → move in +y
        # This is the SAME logic as R_global @ t_step from Day 17
        # Local "forward" gets rotated by heading angle into world frame

        self.state = np.array([x_new, y_new, theta_new])

        # ─── Jacobian F — linearization of motion model ───
        # The "Extended" part: motion model has sin/cos (nonlinear)
        # Kalman Filter needs linear math. Jacobian approximates
        # the nonlinear function as a matrix at the current point.
        # Think of it as the slope of a curve at one specific point.
        F = np.array([
            [1, 0, -v * np.sin(theta) * dt],
            [0, 1,  v * np.cos(theta) * dt],
            [0, 0,  1]
        ])
        # WHY these values: partial derivatives of motion equations
        # Row 1: dx_new/dx=1, dx_new/dy=0, dx_new/dtheta=-v*sin(theta)*dt
        # The -v*sin(theta)*dt term: if heading changes slightly,
        # the x-prediction changes by this much. That's sensitivity.

        # ─── Covariance prediction ────────────────────────
        # Uncertainty GROWS during prediction
        # F @ P @ F.T: propagate current uncertainty through motion model
        # + Q: add IMU noise on top
        self.P = F @ self.P @ F.T + self.Q
        # WHY F @ P @ F.T: if your motion model amplifies uncertainty
        # in certain directions, this captures that
        # WHY + Q: each prediction step adds fresh IMU noise
        # This is WHY uncertainty grows every predict step

    def update(self, z_x, z_y):
        """
        UPDATE STEP — use camera/VO measurement to correct prediction.

        "IMU predicted I'm at (3.0, 2.0). Camera says I'm at (3.5, 2.1).
        Who do I trust more? Blend them based on uncertainties."

        After this step, uncertainty SHRINKS because we gained
        new independent information.
        """
        # ─── Measurement matrix H ─────────────────────────
        # Maps state [x, y, theta] to measurement [x, y]
        # Camera measures position but NOT heading
        # So H picks out x and y from the state vector
        H = np.array([
            [1, 0, 0],
            [0, 1, 0]
        ])
        # WHY this shape: measurement is 2D (x,y), state is 3D (x,y,theta)
        # H @ state = [x, y] — extracts the measurable parts

        # ─── Innovation (measurement residual) ────────────
        # How far off is our prediction from the actual measurement?
        z = np.array([z_x, z_y])          # camera measurement
        y_residual = z - H @ self.state   # difference: measured - predicted
        # WHY residual: if prediction matches measurement perfectly,
        # residual is zero and no correction needed
        # Large residual = prediction was way off = big correction coming

        # ─── Innovation covariance S ──────────────────────
        # Total uncertainty in the residual: prediction uncertainty + measurement uncertainty
        S = H @ self.P @ H.T + self.R
        # WHY H @ P @ H.T: project state uncertainty into measurement space
        # WHY + R: add measurement noise (camera isn't perfect either)

        # ─── Kalman Gain K ────────────────────────────────
        # THE MAGIC NUMBER — determines how much to trust the measurement
        # K near 1.0 → trust camera more (prediction was uncertain)
        # K near 0.0 → trust prediction more (camera is noisy)
        K = self.P @ H.T @ np.linalg.inv(S)
        # WHY P @ H.T: how uncertain is our prediction?
        # WHY / S: normalize by total uncertainty
        # If P is big (uncertain prediction) and R is small (good camera):
        #   K is large → big correction toward camera measurement
        # If P is small (confident prediction) and R is big (bad camera):
        #   K is small → small correction, mostly trust prediction

        # ─── State update ─────────────────────────────────
        # Correct the state: move toward measurement by K * residual
        self.state = self.state + K @ y_residual
        # WHY K @ y_residual: K scales the correction
        # If K=0.8 and residual=[0.5, 0.1]:
        #   correction = [0.4, 0.08] — mostly trust camera
        # If K=0.2 and residual=[0.5, 0.1]:
        #   correction = [0.1, 0.02] — mostly trust prediction

        # ─── Covariance update ────────────────────────────
        # Uncertainty SHRINKS — we gained new information
        I = np.eye(3)
        self.P = (I - K @ H) @ self.P
        # WHY (I - K @ H): if K is large (big correction),
        # uncertainty shrinks a lot. If K is small (small correction),
        # uncertainty shrinks a little.
        # This is WHY uncertainty shrinks: new measurement
        # always adds information, reducing what we don't know

# Create EKF starting at true initial position
ekf = EKF(true_x[0], true_y[0], true_theta[0])
print(f"EKF initialized at ({true_x[0]:.1f}, {true_y[0]:.1f})")
print(f"Initial uncertainty (P diagonal): {np.diag(ekf.P)}")
print(f"Process noise Q diagonal: {np.diag(ekf.Q)}")
print(f"Measurement noise R diagonal: {np.diag(ekf.R)}")

# ─── Run the EKF fusion loop ──────────────────────────────

# Storage for results
ekf_x, ekf_y = [], []             # EKF fused estimate
ekf_uncertainty = []                # trace of P (total uncertainty)

imu_only_x, imu_only_y = [], []   # IMU dead reckoning (no correction)
imu_state = np.array([true_x[0], true_y[0], true_theta[0]])
# WHY track IMU-only: to show how badly it drifts WITHOUT camera correction
# This proves the EKF is actually helping

vo_used_x, vo_used_y = [], []     # VO measurements (when available)

for i in range(n_steps):
    # ─── EKF PREDICT (every frame — IMU always available) ──
    ekf.predict(imu_v[i], imu_omega[i], dt)
    # WHY every frame: IMU never goes blind
    # Each predict: state moves forward, uncertainty GROWS

    # ─── IMU-only tracking (for comparison) ────────────────
    # Same motion model as EKF predict, but NO correction ever
    x, y, theta = imu_state
    imu_state = np.array([
        x + imu_v[i] * np.cos(theta) * dt,
        y + imu_v[i] * np.sin(theta) * dt,
        theta + imu_omega[i] * dt
    ])
    imu_only_x.append(imu_state[0])
    imu_only_y.append(imu_state[1])
    # WHY track this separately: shows pure IMU drift
    # After 200 steps, this will be FAR from truth

    # ─── EKF UPDATE (only when camera sees features) ──────
    if vo_available[i]:
        ekf.update(vo_x[i], vo_y[i])
        vo_used_x.append(vo_x[i])
        vo_used_y.append(vo_y[i])
        # WHY conditional: camera goes blind frames 60-100
        # During blackout: predict-predict-predict, no correction
        # Uncertainty balloons during this gap

    # ─── Store results ─────────────────────────────────────
    ekf_x.append(ekf.state[0])
    ekf_y.append(ekf.state[1])

    # Trace of P = sum of diagonal = total uncertainty across all states
    ekf_uncertainty.append(np.trace(ekf.P))
    # WHY trace: single number summarizing total uncertainty
    # trace = P[0,0] + P[1,1] + P[2,2] = x_var + y_var + theta_var

# ─── Compute errors ───────────────────────────────────────
ekf_error = np.sqrt((np.array(ekf_x) - true_x)**2 +
                     (np.array(ekf_y) - true_y)**2)
imu_error = np.sqrt((np.array(imu_only_x) - true_x)**2 +
                     (np.array(imu_only_y) - true_y)**2)
# WHY sqrt(dx^2 + dy^2): Euclidean distance from true position
# This is the position error at each timestep

print(f"Final position errors:")
print(f"  IMU only:  {imu_error[-1]:.2f} meters")
print(f"  EKF fused: {ekf_error[-1]:.2f} meters")
print(f"  Improvement: {imu_error[-1]/ekf_error[-1]:.1f}x better")
print(f"\nMax error during VO blackout (frames 60-100):")
print(f"  EKF: {np.max(ekf_error[60:100]):.2f} meters")
print(f"  IMU: {np.max(imu_error[60:100]):.2f} meters")
print(f"\nFinal uncertainty (trace of P): {ekf_uncertainty[-1]:.4f}")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

# ─── Plot 1: Trajectories ─────────────────────────────────
ax = axes[0][0]
ax.plot(true_x, true_y, 'g-', linewidth=2, label='Ground truth', zorder=3)
ax.plot(imu_only_x, imu_only_y, 'r--', linewidth=1.5, alpha=0.7, label='IMU only (drifts)')
ax.plot(ekf_x, ekf_y, 'b-', linewidth=1.5, label='EKF fused', zorder=2)
ax.scatter(vo_used_x, vo_used_y, c='orange', s=5, alpha=0.3, label='VO measurements', zorder=1)

# Mark the blackout region
blackout_x = [ekf_x[i] for i in range(60, 100)]
blackout_y = [ekf_y[i] for i in range(60, 100)]
ax.plot(blackout_x, blackout_y, 'b-', linewidth=3, alpha=0.5)
ax.annotate('Camera blind\n(frames 60-100)',
            xy=(blackout_x[20], blackout_y[20]),
            xytext=(0, -3), fontsize=11, fontweight='bold', color='red',
            arrowprops=dict(arrowstyle='->', color='red'))

ax.set_title('Trajectory Comparison', fontsize=14, fontweight='bold')
ax.set_xlabel('X (meters)')
ax.set_ylabel('Y (meters)')
ax.legend(loc='upper left', fontsize=10)
ax.set_aspect('equal')
ax.grid(True, alpha=0.3)

# ─── Plot 2: Position Error Over Time ─────────────────────
ax = axes[0][1]
time = np.arange(n_steps) * dt
ax.plot(time, imu_error, 'r-', linewidth=1.5, alpha=0.7, label='IMU only error')
ax.plot(time, ekf_error, 'b-', linewidth=1.5, label='EKF error')
ax.axvspan(6.0, 10.0, alpha=0.15, color='red', label='Camera blackout')
ax.set_title('Position Error Over Time', fontsize=14, fontweight='bold')
ax.set_xlabel('Time (seconds)')
ax.set_ylabel('Error (meters)')
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)

# ─── Plot 3: Uncertainty (Trace of P) ─────────────────────
ax = axes[1][0]
ax.plot(time, ekf_uncertainty, 'b-', linewidth=1.5)
ax.axvspan(6.0, 10.0, alpha=0.15, color='red', label='Camera blackout')
ax.set_title('EKF Uncertainty Over Time', fontsize=14, fontweight='bold')
ax.set_xlabel('Time (seconds)')
ax.set_ylabel('Trace of P (total uncertainty)')
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)

# Annotate the uncertainty spike
blackout_start_unc = ekf_uncertainty[60]
blackout_peak_unc = max(ekf_uncertainty[60:100])
recovery_unc = ekf_uncertainty[105]
ax.annotate(f'Blackout start: {blackout_start_unc:.2f}',
            xy=(6.0, blackout_start_unc), fontsize=9,
            xytext=(2.0, blackout_peak_unc * 0.8),
            arrowprops=dict(arrowstyle='->', color='gray'))
ax.annotate(f'Peak: {blackout_peak_unc:.2f}',
            xy=(10.0, blackout_peak_unc), fontsize=9,
            xytext=(12.0, blackout_peak_unc * 0.9),
            arrowprops=dict(arrowstyle='->', color='gray'))
ax.annotate(f'Recovery: {recovery_unc:.2f}',
            xy=(10.5, recovery_unc), fontsize=9,
            xytext=(13.0, recovery_unc + 0.3),
            arrowprops=dict(arrowstyle='->', color='gray'))

# ─── Plot 4: Kalman Gain Behavior ─────────────────────────
ax = axes[1][1]

# Re-run EKF just to capture Kalman gains
ekf2 = EKF(true_x[0], true_y[0], true_theta[0])
k_gains = []
for i in range(n_steps):
    ekf2.predict(imu_v[i], imu_omega[i], dt)
    if vo_available[i]:
        H = np.array([[1,0,0],[0,1,0]])
        S = H @ ekf2.P @ H.T + ekf2.R
        K = ekf2.P @ H.T @ np.linalg.inv(S)
        k_gains.append(np.trace(K))  # total gain magnitude
        ekf2.update(vo_x[i], vo_y[i])
    else:
        k_gains.append(0)  # no update = no gain

ax.plot(time, k_gains, 'purple', linewidth=1.5)
ax.axvspan(6.0, 10.0, alpha=0.15, color='red', label='Camera blackout')
ax.set_title('Kalman Gain Over Time', fontsize=14, fontweight='bold')
ax.set_xlabel('Time (seconds)')
ax.set_ylabel('Kalman Gain (trace of K)')
ax.legend(fontsize=10)
ax.grid(True, alpha=0.3)
ax.annotate('Gain SPIKES after blackout\n= trusts camera MORE',
            xy=(10.1, max(k_gains[100:110])), fontsize=9, color='purple',
            xytext=(12, max(k_gains[100:110]) * 0.8),
            arrowprops=dict(arrowstyle='->', color='purple'))

plt.tight_layout()
plt.show()

print("\nKey observations:")
print(f"1. IMU-only (red) drifts away from the circle — never recovers")
print(f"2. EKF (blue) stays close to truth (green) — camera corrections prevent drift")
print(f"3. During blackout, EKF uncertainty SPIKES (bottom-left)")
print(f"4. After blackout, Kalman gain SPIKES (bottom-right) — EKF trusts camera more")
print(f"5. Uncertainty drops immediately when camera returns — one update fixes it")

