# -*- coding: utf-8 -*-
"""Kmeans_Testing_Day30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTOYKCPqhXvNu5-g7zf1E5iubdx_lskX
"""

import cv2
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt

# Step 1: Load images and extract ORB descriptors
# Using 5 sample images — in real ORB-SLAM3 this would be millions

# Create synthetic "rooms" — images with distinct patterns
def create_room_image(seed, label):
    np.random.seed(seed)
    img = np.zeros((480, 640), dtype=np.uint8)

    # Add random rectangles and circles to create texture
    for _ in range(20):
        x1, y1 = np.random.randint(0, 600), np.random.randint(0, 440)
        x2, y2 = x1 + np.random.randint(20, 100), y1 + np.random.randint(20, 100)
        color = np.random.randint(50, 255)
        cv2.rectangle(img, (x1, y1), (x2, y2), int(color), -1)

    for _ in range(10):
        cx, cy = np.random.randint(50, 590), np.random.randint(50, 430)
        radius = np.random.randint(10, 50)
        color = np.random.randint(50, 255)
        cv2.circle(img, (cx, cy), radius, int(color), -1)

    return img

# Create 6 "rooms" — room A appears at frames 0, 5 (simulates revisiting)
rooms = {
    'Room A': create_room_image(42, 'A'),
    'Room B': create_room_image(99, 'B'),
    'Room C': create_room_image(17, 'C'),
    'Room D': create_room_image(55, 'D'),
    'Room E': create_room_image(73, 'E'),
}

# Simulate a robot path: A → B → C → D → E → A (back to start!)
frame_sequence = ['Room A', 'Room B', 'Room C', 'Room D', 'Room E', 'Room A']

# Extract ORB descriptors from each frame
orb = cv2.ORB_create(nfeatures=300)

all_descriptors = []    # for building vocabulary
frame_descriptors = []  # per-frame descriptors

for room_name in frame_sequence:
    img = rooms[room_name]
    kp, desc = orb.detectAndCompute(img, None)
    all_descriptors.append(desc)
    frame_descriptors.append(desc)
    print(f'{room_name}: {len(kp)} features, descriptor shape: {desc.shape}')

# Combine all descriptors for vocabulary building
all_desc_combined = np.vstack(all_descriptors)
print(f'\nTotal descriptors for vocabulary: {all_desc_combined.shape[0]}')

# Show the rooms
fig, axes = plt.subplots(1, 5, figsize=(20, 4))
for i, (name, img) in enumerate(rooms.items()):
    axes[i].imshow(img, cmap='gray')
    axes[i].set_title(name, fontsize=14)
    axes[i].axis('off')
plt.suptitle('5 Rooms — Robot visits A→B→C→D→E→A (revisits Room A)', fontsize=16)
plt.tight_layout()
plt.show()

# Step 2: Build Vocabulary Tree using Hierarchical K-Means
#
# Think of it like sorting a library:
# Level 1: Split ALL books into 5 broad categories
# Level 2: Split each category into 5 sub-categories → 25 groups
# Level 3: Split each sub-category into 5 → 125 groups (visual words)
#
# Each "group center" is a visual word — a representative descriptor

from scipy.cluster.vq import kmeans2

def build_vocab_tree(descriptors, branch_factor=5, depth=3):
    """
    Build a hierarchical vocabulary tree.

    branch_factor: how many children each node has (K in k-means)
    depth: how many levels deep the tree goes (D)

    Total visual words = branch_factor^depth = 5^3 = 125
    Comparisons to search = branch_factor × depth = 5 × 3 = 15
    """
    # Convert binary descriptors to float for k-means
    # k-means needs continuous values, not binary
    desc_float = descriptors.astype(np.float32)

    # The tree is stored as a list of levels
    # Each level is a list of (center, child_indices) pairs
    tree = []

    # Level 0: all descriptors start in one big group
    current_groups = [desc_float]

    for level in range(depth):
        next_groups = []
        level_centers = []

        for group in current_groups:
            if len(group) < branch_factor:
                # Group too small to split further
                # Each descriptor becomes its own "center"
                for desc in group:
                    level_centers.append(desc)
                    next_groups.append(np.array([desc]))
                continue

            # K-means: split this group into branch_factor clusters
            centers, labels = kmeans2(group, branch_factor, minit='points', iter=20)

            for k in range(branch_factor):
                mask = labels == k
                if np.sum(mask) > 0:
                    level_centers.append(centers[k])
                    next_groups.append(group[mask])

        tree.append(np.array(level_centers))
        current_groups = next_groups
        print(f'Level {level + 1}: {len(level_centers)} nodes')

    # The leaf nodes are our visual words
    visual_words = tree[-1]
    print(f'\nVocabulary: {len(visual_words)} visual words')
    print(f'Search cost: {branch_factor} × {depth} = {branch_factor * depth} comparisons')
    print(f'Brute force would be: {len(visual_words)} comparisons')

    return tree, visual_words


tree, visual_words = build_vocab_tree(all_desc_combined, branch_factor=5, depth=3)

# Step 3: Convert each frame to a "Bag of Words" histogram
#
# For each frame:
#   1. Take its 300 ORB descriptors
#   2. For each descriptor, find the closest visual word
#   3. Count how often each word appears → histogram
#
# The histogram is the frame's "fingerprint" —
# two frames of the same room will have similar histograms

def descriptor_to_word(desc, visual_words):
    """
    Find the closest visual word for one descriptor.
    Uses Euclidean distance on float descriptors.
    In real ORB-SLAM3, this walks the tree (15 comparisons).
    Here we brute-force for simplicity.
    """
    desc_float = desc.astype(np.float32)
    distances = np.sum((visual_words - desc_float) ** 2, axis=1)
    return np.argmin(distances)


def frame_to_histogram(descriptors, visual_words):
    """
    Convert a frame's descriptors into a Bag of Words histogram.

    Think of it like describing a meal:
    "This plate has 3 parts rice, 2 parts chicken, 1 part salad"
    Instead of listing every grain of rice individually.

    The histogram summarizes WHAT visual patterns appear
    and HOW OFTEN — without caring about WHERE in the image.
    """
    num_words = len(visual_words)
    histogram = np.zeros(num_words)

    for desc in descriptors:
        word_id = descriptor_to_word(desc, visual_words)
        histogram[word_id] += 1

    # Normalize — so frames with different numbers of features
    # can be compared fairly (frame with 500 features shouldn't
    # automatically score higher than frame with 200)
    total = np.sum(histogram)
    if total > 0:
        histogram = histogram / total

    return histogram


# Build histogram for each frame
frame_histograms = []
for i, (room_name, desc) in enumerate(zip(frame_sequence, frame_descriptors)):
    hist = frame_to_histogram(desc, visual_words)
    frame_histograms.append(hist)

    # Count how many unique words this frame uses
    words_used = np.sum(hist > 0)
    print(f'Frame {i} ({room_name}): uses {words_used}/{len(visual_words)} visual words')

# Visualize histograms for Frame 0 (Room A first visit) and Frame 5 (Room A second visit)
fig, axes = plt.subplots(2, 1, figsize=(16, 6))

axes[0].bar(range(len(visual_words)), frame_histograms[0], color='green', alpha=0.7)
axes[0].set_title('Frame 0 — Room A (first visit)', fontsize=14)
axes[0].set_ylabel('Frequency')
axes[0].set_xlim(-1, len(visual_words))

axes[1].bar(range(len(visual_words)), frame_histograms[5], color='blue', alpha=0.7)
axes[1].set_title('Frame 5 — Room A (second visit)', fontsize=14)
axes[1].set_ylabel('Frequency')
axes[1].set_xlabel('Visual Word ID')
axes[1].set_xlim(-1, len(visual_words))

plt.suptitle('Same room → Similar histograms!', fontsize=16)
plt.tight_layout()
plt.show()

# Step 4: Loop Closure Detection using Histogram Similarity
#
# Compare every pair of frames using cosine similarity.
# Cosine similarity measures how "aligned" two histograms are:
#   1.0 = identical directions (same room)
#   0.0 = completely different
#
# It's like comparing two recipes:
# Both have lots of rice and chicken → similar (same dish)
# One has rice, other has pasta → different (different dish)

def cosine_similarity(hist1, hist2):
    """
    Dot product of two normalized vectors.
    Measures the angle between them — small angle = similar.
    """
    dot = np.dot(hist1, hist2)
    norm1 = np.linalg.norm(hist1)
    norm2 = np.linalg.norm(hist2)
    if norm1 == 0 or norm2 == 0:
        return 0.0
    return dot / (norm1 * norm2)


# Compare ALL pairs of frames
num_frames = len(frame_histograms)
similarity_matrix = np.zeros((num_frames, num_frames))

print("Similarity scores (cosine similarity):\n")
for i in range(num_frames):
    for j in range(num_frames):
        sim = cosine_similarity(frame_histograms[i], frame_histograms[j])
        similarity_matrix[i][j] = sim

# Print similarity matrix
header = "        " + "  ".join([f"F{j}({frame_sequence[j][:3]})" for j in range(num_frames)])
print(header)
for i in range(num_frames):
    row = f"F{i}({frame_sequence[i][:3]}) "
    for j in range(num_frames):
        row += f"  {similarity_matrix[i][j]:.3f}     "
    print(row)

# Find loop closure — highest similarity between non-adjacent frames
print("\n\nLoop Closure Detection:")
print("=" * 50)

best_score = 0
best_pair = (0, 0)

for i in range(num_frames):
    for j in range(i + 2, num_frames):  # skip adjacent frames (i+1)
        sim = similarity_matrix[i][j]
        if sim > best_score:
            best_score = sim
            best_pair = (i, j)
        if sim > 0.7:  # threshold for loop closure candidate
            print(f"  Frame {i} ({frame_sequence[i]}) ↔ Frame {j} ({frame_sequence[j]}): "
                  f"similarity = {sim:.3f} ✓ LOOP CLOSURE CANDIDATE")

print(f"\nBest match: Frame {best_pair[0]} ({frame_sequence[best_pair[0]]}) ↔ "
      f"Frame {best_pair[1]} ({frame_sequence[best_pair[1]]}) "
      f"— similarity: {best_score:.3f}")

# Visualize similarity matrix
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Heatmap
im = axes[0].imshow(similarity_matrix, cmap='YlOrRd', vmin=0, vmax=1)
axes[0].set_xticks(range(num_frames))
axes[0].set_yticks(range(num_frames))
axes[0].set_xticklabels([f'F{i}\n{frame_sequence[i][:6]}' for i in range(num_frames)])
axes[0].set_yticklabels([f'F{i} {frame_sequence[i][:6]}' for i in range(num_frames)])
axes[0].set_title('Frame Similarity Matrix', fontsize=14)
plt.colorbar(im, ax=axes[0], label='Cosine Similarity')

# Add similarity values in cells
for i in range(num_frames):
    for j in range(num_frames):
        axes[0].text(j, i, f'{similarity_matrix[i][j]:.2f}',
                     ha='center', va='center', fontsize=10,
                     color='white' if similarity_matrix[i][j] > 0.6 else 'black')

# Bar chart — similarity of each frame to Frame 0
sims_to_f0 = [similarity_matrix[0][j] for j in range(num_frames)]
colors = ['green' if frame_sequence[j] == 'Room A' else 'gray' for j in range(num_frames)]
axes[1].bar(range(num_frames), sims_to_f0, color=colors)
axes[1].set_xticks(range(num_frames))
axes[1].set_xticklabels([f'F{i}\n{frame_sequence[i][:6]}' for i in range(num_frames)])
axes[1].set_ylabel('Similarity to Frame 0')
axes[1].set_title('Which frame looks most like Frame 0?', fontsize=14)
axes[1].axhline(y=0.7, color='red', linestyle='--', label='Loop closure threshold')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"\nDay 20 approach: compare {num_frames} × 300 descriptors = slow")
print(f"Vocabulary tree: compare {num_frames} histograms of length 125 = fast")
print(f"Same result, fraction of the compute.")

